export const FETCH_BANNER_LIST_SUCCESS = "FETCH_BANNER_LIST_SUCCESS"

export const FETCH_BANNER_LIST_ERROR = "FETCH_BANNER_LIST_ERROR"

export const FETCH_BANNER_LIST_BEGIN = "FETCH_BANNER_LIST_BEGIN"
