// 获取轮播图数据
export const FETCH_BANNER_LIST_SUCCESS = "FETCH_BANNER_LIST_SUCCESS"
export const FETCH_BANNER_LIST_ERROR = "FETCH_BANNER_LIST_ERROR"
export const FETCH_BANNER_LIST_BEGIN = "FETCH_BANNER_LIST_BEGIN"

// 获取热门推荐
export const PERSONALIZED_TYPE_SUCCESS = "PERSONALIZED_TYPE_SUCCESS"
